const {test}=require('node:test');
const assert=require('node:assert/strict');
const load=()=>import('../src/domain.mjs');
const now=Date.UTC(2026,8,21,8);
test('commute: online, 5 km boundary, round-trip and distance surcharge',async()=>{const {commute}=await load();assert.equal(commute(5,'线下'),0);assert.equal(commute(8,'线下'),5500);assert.equal(commute(20,'线上'),0);assert.equal(commute(20,'线下'),13330);assert.ok(commute(5.1,'线下')>0);});
test('matches all weekly sessions at a single feasible base rate',async()=>{const {createState,initialRequest,match}=await load();const s=createState(now),r=initialRequest(),a=match(s,r,now);assert.equal(a.length,3);for(const c of a){assert.equal(c.slots.length,2);for(const slot of c.slots){const effective=c.rate+c.commute/((slot.end-slot.start)/60);assert.ok(effective>=r.budgetMin&&effective<=r.budgetMax);}}r.distance=8;r.budgetMin=26000;r.budgetMax=27000;s.tutors=s.tutors.filter(t=>t.id==='t1');assert.equal(match(s,r,now).length,0,'one-hour and two-hour allowed rate intersections must overlap');});
test('alternatives, actual duration and duplicate-session exclusion',async()=>{const {createState,initialRequest,match}=await load();const s=createState(now),r=initialRequest();r.sessions[0].options=[{day:1,start:1140,end:1200}];assert.equal(match(s,r,now).length,0);r.sessions[0].options.push({day:3,start:1140,end:1200});assert.ok(match(s,r,now).length);r.sessions=[{options:[{day:3,start:1140,end:1200}]},{options:[{day:3,start:1140,end:1200}]}];assert.equal(match(s,r,now).length,0);r.sessions[0].options[0].end=1170;assert.throws(()=>match(s,r,now));});
test('hard constraints: subjects, gender, expiry, commuting and city',async()=>{const {createState,initialRequest,match}=await load();let s=createState(now),r=initialRequest();r.gender='女';assert.equal(match(s,r,now).length,2);r.subjects=['英语'];assert.equal(match(s,r,now)[0].tutor.id,'t4');s.tutors.forEach(t=>t.verifiedUntil=now-1);assert.equal(match(s,r,now).length,0);s=createState(now);r=initialRequest();r.distance=8;s.tutors.forEach(t=>t.far=false);assert.equal(match(s,r,now).length,0);r.mode='均可';r.city='杭州';assert.ok(match(s,r,now).every(c=>c.mode==='线上'));r.mode='线下';assert.throws(()=>match(s,r,now));});
test('multi-subject requests require one tutor to cover every selected subject',async()=>{const {createState,initialRequest,match,migrateState}=await load();const s=createState(now),r=initialRequest();r.subjects=['数学','物理'];assert.ok(match(s,r,now).every(c=>r.subjects.every(subject=>c.tutor.subjects.includes(subject))));r.subjects=['政治','历史','地理'];assert.deepEqual(match(s,r,now).map(c=>c.tutor.id),['t7']);r.subjects=['数学','政治'];assert.equal(match(s,r,now).length,0);assert.throws(()=>match(s,{...r,subjects:[]},now));const old={version:1,tutors:s.tutors.slice(0,6),orders:[{request:{subject:'英语'}}],request:{subject:'数学'}};const migrated=migrateState(old);assert.equal(migrated.version,2);assert.deepEqual(migrated.request.subjects,['数学']);assert.deepEqual(migrated.orders[0].request.subjects,['英语']);assert.ok(migrated.tutors.some(t=>t.id==='t7'));});
test('validation: numeric bounds and fixed price boundary',async()=>{const {createState,initialRequest,match}=await load();const s=createState(now),r=initialRequest();r.budgetMin=25000;r.budgetMax=25000;assert.ok(match(s,r,now).length);r.budgetMax=31000;assert.throws(()=>match(s,r,now));r.budgetMax=NaN;assert.throws(()=>match(s,r,now));});
test('24-hour invite locks and expiry release',async()=>{const {createState,initialRequest,invite,match,expire,HOUR}=await load();const s=createState(now),r=initialRequest(),o=invite(s,r,'t1',now);assert.ok(!match(s,r,now).some(c=>c.tutor.id==='t1'));assert.throws(()=>invite(s,r,'t2',now));expire(s,now+24*HOUR);assert.equal(o.status,'expired');assert.ok(match(s,r,now+24*HOUR).some(c=>c.tutor.id==='t1'));});
async function trial(){const d=await load(),s=d.createState(now),o=d.invite(s,d.initialRequest(),'t1',now);for(const [a,r] of [['accept','tutor'],['confirmTrial','parent'],['payTrial','parent'],['receive','tutor'],['finish','tutor']])d.act(s,o.id,a,r,now);return {d,s,o};}
test('both successes charge once, no commute in fee, successful slots remain blocked',async()=>{const {d,s,o}=await trial();d.act(s,o.id,'success','parent',now);assert.equal(o.status,'review');assert.equal(o.parentFee,undefined);d.act(s,o.id,'success','tutor',now);assert.equal(o.status,'success');assert.equal(o.parentFee,Math.round(o.quote.rate/2));assert.equal(o.tutorFee,o.quote.rate);const t=s.tutors[0];assert.equal(t.blocks.length,2);assert.equal(t.active,false);assert.throws(()=>d.act(s,o.id,'success','tutor',now));d.act(s,o.id,'payService','parent',now);d.act(s,o.id,'payService','parent',now);assert.equal(o.parentPaid,true);assert.equal(t.blocks.length,2);t.active=true;assert.ok(!d.match(s,d.initialRequest(),now).some(c=>c.tutor.id===t.id));});
test('failure and missing confirmation never generate fees',async()=>{let {d,s,o}=await trial();d.act(s,o.id,'success','parent',now);d.act(s,o.id,'fail','tutor',now);assert.equal(o.status,'failed');assert.equal(o.parentFee,undefined);assert.ok(d.match(s,d.initialRequest(),now).some(c=>c.tutor.id==='t1'));({d,s,o}=await trial());d.act(s,o.id,'success','parent',now);d.expire(s,now+72*d.HOUR);assert.equal(o.status,'unconfirmed');assert.equal(o.parentFee,undefined);assert.throws(()=>d.act(s,o.id,'success','tutor',now+73*d.HOUR));});
test('trial arrangement is recorded before payment',async()=>{const d=await load(),s=d.createState(now),o=d.invite(s,d.initialRequest(),'t1',now);d.act(s,o.id,'accept','tutor',now);assert.equal(o.status,'arranging');assert.throws(()=>d.act(s,o.id,'payTrial','parent',now));d.act(s,o.id,'confirmTrial','parent',now);assert.equal(o.status,'accepted');assert.equal(o.trial.rate,o.quote.rate);assert.equal(o.trial.place,o.request.location);});
test('student onboarding adds a verified, matchable demo profile',async()=>{const d=await load(),s=d.createState(now);const t=d.addDemoTutor(s,{email:'demo@fudan.edu.cn',name:'测试同学',major:'历史学系',year:'大二',gender:'女',grades:['高中'],subjects:['历史'],mode:'线上',far:false,low:220,high:250,slots:['周三晚'],style:'耐心型'},now);assert.ok(t.verifiedUntil>now);assert.ok(s.tutors.includes(t));const r=d.initialRequest();r.subjects=['历史'];r.mode='线上';r.sessions=[{options:[{day:3,start:1140,end:1200}]}];assert.ok(d.match(s,r,now).some(x=>x.tutor.id===t.id));});
test('no-match diagnosis returns the first actionable hard constraint',async()=>{const d=await load(),s=d.createState(now),r=d.initialRequest();r.subjects=['数学','政治'];assert.equal(d.diagnose(s,r,now)[0].code,'subjects');r.subjects=['数学'];r.gender='女';s.tutors.filter(t=>t.gender==='女').forEach(t=>t.active=false);assert.equal(d.diagnose(s,r,now)[0].code,'gender');});
test('wrong roles and jumping past payment are rejected',async()=>{const d=await load(),s=d.createState(now),o=d.invite(s,d.initialRequest(),'t1',now);assert.throws(()=>d.act(s,o.id,'accept','parent',now));assert.throws(()=>d.act(s,o.id,'finish','tutor',now));assert.throws(()=>d.act(s,o.id,'payService','parent',now));d.act(s,o.id,'accept','tutor',now);assert.throws(()=>d.act(s,o.id,'confirmTrial','tutor',now));d.act(s,o.id,'confirmTrial','parent',now);d.act(s,o.id,'payTrial','parent',now);assert.throws(()=>d.act(s,o.id,'cancel','parent',now));});
